common_args:
  training_type: "cross_silo"
  random_seed: 0

data_args:
  dataset: "mnist"
#  dataset: "cifar10"
#  data_cache_dir: "../data/cifar10"
  data_cache_dir: "../data/mnist"
  partition_method: "homo"
  partition_alpha: 0.5

model_args:
  model: "cnn" # 使用自定义的lenet5

train_args:
  federated_optimizer: "FedAvg" # 本实现使用自定义的FedAvg，
  client_id_list: "[]"
  client_num_in_total: 20
  client_num_per_round: 10 # 与下面的worker_num一样
  comm_round: 100
  epochs: 1
  batch_size: 32
  client_optimizer: sgd
  learning_rate: 0.03
  weight_decay: 0.001

validation_args:
  frequency_of_the_test: 1

device_args:
  worker_num: 10
  using_gpu: false
  gpu_id: 0

comm_args:
  backend: "GRPC"
  grpc_ipconfig_path: '../../conf/grpc_ipconfig.csv'

tracking_args:
  log_file_dir: ./log
  enable_wandb: false
  wandb_key: ee0b5f53d949c84cee7decbe7a629e63fb2f8408
  wandb_entity: fml-ai
  wandb_project: simulation
  run_name: fedml_torch_fedavg_mnist_lenet5